Trigger observers when TweenCompleted event is sent
djeedai/bevy_tweening pull request #133
Opened 2024-07-27 02:39 UTC by Peepo-Juice

This PR is very simple: trigger observers when the TweenCompleted event gets sent out. I added this right next to event.send() so it will always happen if use "with_completed_event".

However, we may want to add an equivalent to "with_completed_event" so its opt-in, i.e. "with_completed_trigger" and "with_completed_trigger_targets".

For now, this is the easiest solution to get the ball rolling on this.

2024-11-24 23:40 UTC, musjj commented
@djeedai 

Any chance this can get merged soon? Observers make it a lot easier to deal with entity-based events. It looks like that the only failing check is the decreased coverage, but I don't see how that can be improved (false negative?).

2024-11-26 12:19 UTC, musjj commented on src/tweenable.rs
> +                commands.trigger(event);
This shouldn't be necessary, world-scoped observers should be able to see entity-scoped triggers too.

```suggestion
```

2024-11-26 12:19 UTC, musjj commented on src/tweenable.rs
> +                commands.trigger_targets(event, [entity]);
A small nit, but you don't need an array:
```suggestion
                commands.trigger_targets(event, entity);
```

2024-12-02 22:48 UTC, musjj commented on src/tweenable.rs
> +                commands.trigger_targets(event, [entity]);
You forgot this one :slightly_smiling_face: 

```suggestion
                // trigger all entity-scoped observers
                commands.trigger_targets(event, entity);
```

2024-12-09 18:56 UTC, djeedai requested changes

2024-12-09 18:56 UTC, djeedai commented on src/tweenable.rs
> +
Can you please remove that extra blank line, which will also re-trigger a CI against the latest version (with Bevy 0.15 support)? Thanks

2024-12-09 19:23 UTC, djeedai approved these changes

2024-12-09 19:24 UTC, merged